ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        watch:
          - classes   # <-- auto-reload watches compiled classes
    development: true
postgres:
  url: "jdbc:postgresql://localhost:5432/my_database"
  user: "Admin"
  password: "secret"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
jwt:
  issuer: "http://0.0.0.0:8080"
  domain: "http://0.0.0.0:8080"
  audience: "users"
  realm: "Ktor event management app"